### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by daniel218-cyber** [Ripper99-x/CS2-Internal#10]
I saw that you implemented xorstr, if i change and optimize things in the source + having xorstr, then it should be pretty much ud right?

**Comment by Ripper99-x** [comment]
There's pretty much nothing you can "optimize" to make it safer, other than replacing the Present Detour with something safer.

Cheat is read only, at the moment, with the exception of the Detour.

You also have think about the injector you use, if you use any user mode injector, you're exposed to NtQueryVirtualMemory and they can find your memory.

**Comment by Ripper99-x** [comment]
Still, they can detect your memory from user-mode.

So unless you make it look like a legit DLL, it'll be kinda suspicious to VAC.
