### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by dethlux** [Ripper99-x/CS2-Internal#2]
Injection before cs2 menu load up freezes the game via dll hijack and via manual map.

**Comment by Ripper99-x** [comment]
Make sure you are borderless or in windowed mode.

And make sure you delay the injection 2-3 seconds after Valve Logo Screen, because the hack does a pattern scan for SwapChain virtual table to replace it with a custom one, for present function,

**Comment by dethlux** [comment]
I've tried to delay the execution but because I use dll hijack it waits for the dll to fully load before it may continue. I have hijacked the last dll to load into cs2 but it still freezes the game. I am in windowed mode to test. Can you suggest where I can add the delay?
