### ISSUE TITLE
Crash on inject.

### ISSUE THREAD

**Issue by Kumarbaging** [Ripper99-x/CS2-Internal#3]
used injector : https://www.unknowncheats.me/forum/counter-strike-2-a/606455-cs2-injector.html

crashing after injection

**Comment by Kumarbaging** [comment]
// note

tested injection methods ; loadlib , manual map (debug/release versions)
tested res : fullscreen , windowed , fullscreen windowed

**Comment by Ripper99-x** [comment]
The injector you're using it's bad, check the comments in the thread.
I usually injected it with kernel injector, but user mode it's just fine aswsell, just manual map with an working injector.

**Comment by Kumarbaging** [comment]
i tested with the og injector too (aka extreme injector from unknowncheats) , also can u open discord server special for this project? so we can report bugs and help you

**Comment by Kumarbaging** [comment]
thats the debug logs

https://prnt.sc/HjXeyhVmrF9t
https://prnt.sc/ElaoKjvNNJ96

**Comment by Ripper99-x** [comment]
> thats the debug logs
> 
> https://prnt.sc/HjXeyhVmrF9t https://prnt.sc/ElaoKjvNNJ96

Pushed an update rn, it was the findgadget function, I removed the returnaddress spoofer for present hook, cause it's kinda useless anyway, and replaced shadowvmt hook with detour.

All work good.

**Comment by Kumarbaging** [comment]
yup it works perfect
