### ISSUE TITLE
Todo list if you where to add more stuff.

### ISSUE THREAD

**Issue by lola123iuj** [Ripper99-x/CS2-Internal#4]
**Legitbot:**
Visible only
Ignore flash
Ignore smoke
Recoil control

**Visuals:**
Chams 
Chams matrials 
Chams invisible/Visible (And changable color)
Flags (Scoped, Defusing, money, ping, Grabbing hostage and more)

**Misc:** 
third person
Force third person when spectating
Radar
Hitsound
Draw logs
FOV Changer
Remove smoke
Remove flash
Spectator list
Keybind list (Right click on any checkbox and you can Keybind it.)

**Movement:**
Edge jump
Bunny hop
Easy Strafe (WSAD Strafe)
Normal strafe (Mouse Strafe)
Air duck

**Config:**
Config system

### Maybe skin changer idk.

idk its just an suggestion if you where to add more stuff the cheat.

**Comment by Ripper99-x** [comment]
I can do most of them easily, but right now CS2 is kinda boring for me ngl.

If I'll ever be in mood to write some code for CS2, I'll add some stuff you requested.

**Comment by vapew** [comment]
> I can do most of them easily, but right now CS2 is kinda boring for me ngl.
> 
> If I'll ever be in mood to write some code for CS2, I'll add some stuff you requested.

Can you add a visible check for now? aimbot looks pretty bad without

**Comment by weedptr** [comment]
can u maybe add silent aim, fix trigger and a bit more AND push it to git?
