### ISSUE TITLE
Aimbot and BoneESP not working

### ISSUE THREAD

**Issue by Sigma12456** [Ripper99-x/CS2-Internal#9]
Everything works but BoneESP and AimBot

**Comment by Ripper99-x** [comment]
FIXED

**Comment by Sigma12456** [comment]
> FIXED

How did u get the patterns

**Comment by Ripper99-x** [comment]
I just did it myself

> > FIXED
> 
> How did u get the patterns

I just did them myself

**Comment by zyrixmotion** [comment]
Ye i want to know how to use the hex values from offset dumper and  convert it to bytearray. like how did you do. please explain

**Comment by Ripper99-x** [comment]
There's nothing to explain more than this. 
Put a breakpoint on whatever you want to sig, check what accessed that value (Ex: Health, bone array, iteamnum etc..). Then just create your own pattern and search for it to see if it's unique lol.
